
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class department extends javax.swing.JFrame {
    String dept_name;
    static Connection connection=null;
    static String databasename="database";
    static String url= "jdbc:mysql://localhost/"+databasename+"?user="+databasename+"&password="+databasename+"&useUnicode=true&characterEncoding=UTF-8";
    //static String url="jdbc:mysql://localhost=3306/"+databasename;
    static String username="root";
    static String password="root";
    public department() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cse = new javax.swing.JRadioButton();
        eee = new javax.swing.JRadioButton();
        ce = new javax.swing.JRadioButton();
        bba = new javax.swing.JRadioButton();
        eng = new javax.swing.JRadioButton();
        law = new javax.swing.JRadioButton();
        save = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        dept_code = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Department code");

        buttonGroup1.add(cse);
        cse.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cse.setText("CSE");

        buttonGroup1.add(eee);
        eee.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        eee.setText("EEE");

        buttonGroup1.add(ce);
        ce.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ce.setText("CE");

        buttonGroup1.add(bba);
        bba.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bba.setText("BBA");

        buttonGroup1.add(eng);
        eng.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        eng.setText("ENG");

        buttonGroup1.add(law);
        law.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        law.setText("LAW");

        save.setBackground(new java.awt.Color(0, 153, 0));
        save.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        save.setForeground(new java.awt.Color(255, 0, 0));
        save.setText("Next");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Department name");

        dept_code.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9", "10", "11", "12" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Bangladesh Army International University of Science and Technology ");
        jLabel3.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(save)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(79, 79, 79)
                                    .addComponent(dept_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(130, 130, 130)
                                    .addComponent(cse)
                                    .addGap(40, 40, 40)
                                    .addComponent(eee))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(51, 51, 51)
                                    .addComponent(jLabel1))))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ce)
                                .addGap(44, 44, 44)
                                .addComponent(eng)
                                .addGap(29, 29, 29)
                                .addComponent(bba)
                                .addGap(26, 26, 26)
                                .addComponent(law)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dept_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cse)
                    .addComponent(eee)
                    .addComponent(ce)
                    .addComponent(eng)
                    .addComponent(bba)
                    .addComponent(law))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(save)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            connection=DriverManager.getConnection(url,username,password);
            String query="insert into department(dept_code, dept_name)values(?, ?)";
            PreparedStatement pst=connection.prepareStatement(query);
            String dc;
            dc=dept_code.getSelectedItem().toString();
            pst.setString(1,dc);
            if(cse.isSelected()){
                dept_name="CSE";
            }
            if(eee.isSelected()){
                dept_name="EEE";
            }
            if(ce.isSelected()){
                dept_name="CE";
            }
            if(eng.isSelected()){
                dept_name="ENG";
            }
            if(bba.isSelected()){
                dept_name="BBA";
            }
            if(law.isSelected()){
                dept_name="LAW";
            }
            pst.setString(2,dept_name);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Create new department");
            course field=new course();
            field.setVisible(true);
            setVisible(false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new department().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bba;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton ce;
    private javax.swing.JRadioButton cse;
    private javax.swing.JComboBox<String> dept_code;
    private javax.swing.JRadioButton eee;
    private javax.swing.JRadioButton eng;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton law;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
